version: '2'
services:
  wordpress:
    image: docker.io/bitnami/wordpress-nginx:5
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - WORDPRESS_DATABASE_HOST=sqlfmg.mysql.database.azure.com
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_DATABASE_PASSWORD=Pinguino1
volumes:
  wordpress_data:
    driver: local
