apiVersion: v1
kind: Service
metadata:
    name: "fmgkubernetes-c9f0"
    labels:
        app: "fmgkubernetes-c9f0"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http80
    - port: 433
      targetPort: 433
      protocol: TCP
      name: https
    selector:
        app: "fmgkubernetes-c9f0"
