apiVersion: v1
kind: Service
metadata:
    name: "fundacionmezquitadegranada-9df8"
    labels:
        app: "fundacionmezquitadegranada-9df8"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "fundacionmezquitadegranada-9df8"