apiVersion: v1
kind: Service
metadata:
    name: "fmgkubernetes-c9f0"
    labels:
        app: "fmgkubernetes-c9f0"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "fmgkubernetes-c9f0"
